services:
    mattermost.listener.kernel_exception:
        class: Creatissimo\MattermostBundle\EventListener\KernelExceptionListener
        arguments:
            - @mattermost.service
            - @mattermost.exception.helper
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    mattermost.listener.command_exception:
        class: Creatissimo\MattermostBundle\EventListener\ConsoleExceptionListener
        arguments:
            - @mattermost.service
            - @mattermost.exception.helper
        tags:
            - { name: kernel.event_listener, event: console.exception }

    mattermost.service:
        class: Creatissimo\MattermostBundle\Services\MattermostService
        arguments:
            - %kernel.environment%
            - @logger

    mattermost.exception.helper:
        class: Creatissimo\MattermostBundle\Services\ExceptionHelper
        arguments:
            - @mattermost.service