services:
    mattermost.helper:
        class: Creatissimo\MattermostBundle\Services\MattermostHelper
        arguments:
            - %kernel.environment%

    mattermost_exception.listener:
        class: Creatissimo\MattermostBundle\Services\ExceptionHandler
        arguments:
            - @logger
            - %kernel.environment%
            - @mattermost.helper
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }